[manifest]
version = "1.0.0"
priority = 0


[[patches]] # Ijiraq Patch 1 (patches properly)
[patches.pattern]
target = "card.lua"
pattern = "self.seal = cardTable.seal"
position = "after"
match_indent = true
payload = '''
self.isIjiraq  = cardTable.isIjiraq
self.visiblyIjiraq = cardTable.visiblyIjiraq
'''
times = 1

[[patches]] # Ijiraq Patch 2 (patches properly)
[patches.pattern]
target = "card.lua"
pattern = "seal = self.seal,"
position = "after"
match_indent = true
payload = '''
isIjiraq = self.isIjiraq,
visiblyIjiraq = self.visiblyIjiraq,
'''
times = 1

[[patches]] # Ijiraq Patch 3 (patches properly)
[patches.pattern]
target = "card.lua"
pattern = "self.children.center.atlas = G.ASSET_ATLAS[(_center.atlas or (_center.set == 'Joker' or _center.consumeable or _center.set == 'Voucher') and _center.set) or 'centers']"
position = "at"
payload = '''
if self.isIjiraq then
    self.children.center.atlas = G.ASSET_ATLAS['IjiraqJokers']
else
    self.children.center.atlas = G.ASSET_ATLAS[(_center.atlas or (_center.set == 'Joker' or _center.consumeable or _center.set == 'Voucher') and _center.set) or 'centers']
end
'''
match_indent = true
times = 1


# Mary unlock check
[[patches]]
[patches.pattern]
match_indent = true
times = 1
target = "functions/state_events.lua"
pattern = "check_for_unlock({type = 'chip_score', chips = math.floor(hand_chips*mult)})"
position = "after"
payload = '''
check_for_unlock({type = 'hpfx_7mult', mult = math.floor(mult)})
'''

# Chud Bloodstone
[[patches]]
[patches.pattern]
match_indent = true
times = 1
target = "card.lua"
pattern = "pseudorandom('bloodstone') < G.GAME.probabilities.normal/self.ability.extra.odds then"
position = "after"
payload = '''
SMODS.calculate_context{hpfx_chudhit = true}
'''

# Chud Hallucination
[[patches]]
[patches.pattern]
match_indent = true 
times = 1
target = "card.lua"
pattern = '''
if context.open_booster then
    if self.ability.name == 'Hallucination' and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
        if pseudorandom('halu'..G.GAME.round_resets.ante) < G.GAME.probabilities.normal/self.ability.extra then
            G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
            G.E_MANAGER:add_event(Event({
                trigger = 'before',
                delay = 0.0,
                func = (function()
'''
position = "after"
payload = '''
SMODS.calculate_context{hpfx_chudhit = true}
'''

# Chudnana
[[patches]]
[patches.pattern]
match_indent = true
times = 1
target = "card.lua"
pattern = '''
if self.ability.name == 'Gros Michel' or self.ability.name == 'Cavendish' then
                    if pseudorandom(self.ability.name == 'Cavendish' and 'cavendish' or 'gros_michel') < G.GAME.probabilities.normal/self.ability.extra.odds then 
                        G.E_MANAGER:add_event(Event({
                            func = function()
'''
position = "after"
payload = '''
SMODS.calculate_context{hpfx_chudhit = true}
'''

# Chud Ball
[[patches]]
[patches.pattern]
match_indent = true
times = 1
target = "card.lua"
pattern = '''
if self.ability.name == '8 Ball' and #G.consumeables.cards + G.GAME.consumeable_buffer < G.consumeables.config.card_limit then
                    if (context.other_card:get_id() == 8) and (pseudorandom('8ball') < G.GAME.probabilities.normal/self.ability.extra) then
                        G.GAME.consumeable_buffer = G.GAME.consumeable_buffer + 1
                        return {
                            extra = {focus = self, message = localize('k_plus_tarot'), func = function()
                                G.E_MANAGER:add_event(Event({
                                    trigger = 'before',
                                    delay = 0.0,
                                    func = (function()
'''
position = "after"
payload = '''
SMODS.calculate_context{hpfx_chudhit = true}
'''

# Space Chud
[[patches]]
[patches.pattern]
match_indent = true
times = 1
target = "card.lua"
pattern = '''
if self.ability.name == 'Space Joker' and pseudorandom('space') < G.GAME.probabilities.normal/self.ability.extra then
    return {
'''
position = "after"
payload = '''
func = function() SMODS.calculate_context({hpfx_chudhit = true}) end,
'''

# Business Chud
[[patches]]
[patches.pattern]
match_indent = true
times = 1
target = "card.lua"
pattern = '''
if self.ability.name == 'Business Card' and
    context.other_card:is_face() and
    pseudorandom('business') < G.GAME.probabilities.normal/self.ability.extra then
'''
position = "after"
payload = '''
SMODS.calculate_context{hpfx_chudhit = true}
'''

# Chud Wheel (The Boss One)
[[patches]]
[patches.pattern]
match_indent = true
times = 1
target = "blind.lua"
pattern = '''
if self.name == 'The Wheel' and pseudorandom(pseudoseed('wheel')) < G.GAME.probabilities.normal/7 then
'''
position = "after"
payload = '''
SMODS.calculate_context{hpfx_chudhit = true}
'''