[manifest]
version = "1.0.0"
priority = 0


[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.seal = cardTable.seal"
position = "after"
match_indent = true
payload = '''
self.isIjiraq  = cardTable.isIjiraq
self.visiblyIjiraq = cardTable.visiblyIjiraq
'''
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "seal = self.seal,"
position = "after"
match_indent = true
payload = '''
isIjiraq = self.isIjiraq,
visiblyIjiraq = self.visiblyIjiraq,
'''
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.children.center.atlas = G.ASSET_ATLAS[(_center.atlas or (_center.set == 'Joker' or _center.consumeable or _center.set == 'Voucher') and _center.set) or 'centers']"
position = "at"
payload = '''
    if self.isIjiraq then
        self.children.center.atlas = G.ASSET_ATLAS['IjiraqJokers']
    else
        self.children.center.atlas = G.ASSET_ATLAS[(_center.atlas or (_center.set == 'Joker' or _center.consumeable or _center.set == 'Voucher') and _center.set) or 'centers']
    end
'''
match_indent = true
times = 1

[[patches]]
[[patches.pattern]]
target = "state_events.lua"
position = "after"
payload = "'check_for_unlock({type = 'hpfx_7mult', mult = math.floor(mult)})'''