[manifest]
version = "1.0.0"
priority = 0

[[patches]] # Blind effect overhaul
[patches.regex]
target = "blind.lua"
pattern = "(?<indent>[\t ]*)(if|elseif) self.name == '(?<blindname>[^']+)'(?<rest>.*)"
position = "at"
line_prepend = "$indent"
payload = "$2 Hyperfixation and Hyperfixation.blind_has_name(self, '$blindname')$rest"
[[patches]]
[patches.regex]
target = "blind.lua"
pattern = "or self.name == '(?<blindname>[^']+)'"
position = "at"
payload = "or (Hyperfixation and Hyperfixation.blind_has_name(self, '$blindname'))"
