[manifest]
version = "1.0.0"
priority = 0

[[patches]] # Post-Discard Context
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
G.GAME.current_round.discards_used = G.GAME.current_round.discards_used + 1
'''
position = "after"
payload = '''
SMODS.calculate_context({hpfx_post_discard = true})
'''
match_indent = true
